updates to lkitty and kitty config

diff --git a/terminal/dot-local/bin/lkitty b/terminal/dot-local/bin/lkitty
--- a/terminal/dot-local/bin/lkitty
+++ b/terminal/dot-local/bin/lkitty
@@ -5,9 +5,9 @@ SEARCH_PATHS=("$HOME")
 
 FILES_PREVIEW="bat --color=always --style=plain {}"
 if command -v lsd >/dev/null 2>&1; then
-  FOLDERS_PREVIEW="lsd --tree --depth=3 --color=always --icon=always {}"
+	FOLDERS_PREVIEW="lsd --tree --depth=3 --color=always --icon=always {}"
 else
-  FOLDERS_PREVIEW="ls --color=always {}"
+	FOLDERS_PREVIEW="ls --color=always {}"
 fi
 
 fzf_command() {
@@ -15,34 +15,43 @@ fzf_command() {
 }
 
 lkitty() {
-  [[ -z $1 ]] && d=$(fd . "${SEARCH_PATHS[@]}" -t d | fzf_command ' KITTY ' "$FOLDERS_PREVIEW") || d="$1"
-  [[ -z $d ]] && exit 1
-  [[ $(kitty @ ls | jq '.[] | select(.is_focused) | .tabs | length') -gt 1 ]] && ltype="os-window" || ltype="overlay-main"
-  nvim_id=$(kitty @ launch --type="$ltype" --cwd="$d" nvim .)
-  kitty @ launch --type=tab --cwd="$d" bash > /dev/null
-  kitty @ focus-window --match "id:$nvim_id"
+	[[ -z $1 ]] && d=$(fd . "${SEARCH_PATHS[@]}" -t d | fzf_command ' KITTY ' "$FOLDERS_PREVIEW") || d="$1"
+	[[ -z $d ]] && exit 1
+	if [[ $(kitty @ ls | jq '.[] | select(.is_focused) | .tabs | length') -eq 1 ]]; then 
+		kitty @ set-tab-title --match "id:$KITTY_WINDOW_ID" "nvim"
+		kitty @ launch --type=tab --cwd="$d" bash > /dev/null
+		kitty @ focus-window --match "id:$KITTY_WINDOW_ID"
+		cd "$d" || return 2
+		nvim .
+	else
+		nvim_id=$(kitty @ launch --type="os-window" --cwd="$d" nvim .)
+		kitty @ set-tab-title --match "id:$nvim_id" "nvim"
+		kitty @ launch --type=tab --cwd="$d" bash > /dev/null
+		kitty @ focus-window --match "id:$nvim_id"
+	fi
 }
 
 lvim() {
-  f=$(fd . "${SEARCH_PATHS[@]}" -t f | fzf_command ' NVIM ' "$FILES_PREVIEW")
-  [[ -z $f ]] && exit 1
-  nvim "$f"
+	f=$(fd . "${SEARCH_PATHS[@]}" -t f | fzf_command ' NVIM ' "$FILES_PREVIEW")
+	[[ -z $f ]] && exit 1
+	kitty @ set-tab-title --match "id:$KITTY_WINDOW_ID" "$(basename "$f")"
+	nvim "$f"
 }
 
 ldir() {
-  f=$(fd . "${SEARCH_PATHS[@]}" -t d | fzf_command ' THUNAR ' "$FOLDERS_PREVIEW")
-  [[ -z $f ]] && exit 1
-  setsid exo-open "$f" >/dev/null 2>&1 
+	f=$(fd . "${SEARCH_PATHS[@]}" -t d | fzf_command ' THUNAR ' "$FOLDERS_PREVIEW")
+	[[ -z $f ]] && exit 1
+	setsid exo-open "$f" >/dev/null 2>&1 
 }
 
 _usage() {
-  echo "Usage: lkitty [options]"
-  echo ""
-  echo "Options:"
-  echo "  -d, --directory DIR   Specify the directory"
-  echo "  -f, --file-manager    Launches file-manager (instead of tmux)"
-  echo "  -v, --vim             Launches nvim (instead of tmux)"
-  echo "  -h, --help            Display this help message"
+	echo "Usage: lkitty [options]"
+	echo ""
+	echo "Options:"
+	echo "	-d, --directory DIR   Specify the directory"
+	echo "	-f, --file-manager    Launches file-manager (instead of tmux)"
+	echo "	-v, --vim             Launches nvim (instead of tmux)"
+	echo "	-h, --help            Display this help message"
 }
 
 dir=""
@@ -53,47 +62,47 @@ ARGS=d:vfh
 LARGS=directory:,vim,file-manager,help
 parse=$(getopt --options $ARGS --longoptions $LARGS --name "lkitty" -- "$@")
 if [[ $? != 0 ]]; then
-  exit 1
+	exit 1
 fi
 eval set -- "$parse"
 
 while true; do
-  case "$1" in
-  -d | --directory)
-    dir="$2"
-    shift 2
-    ;;
-  -v | --vim)
-    v=true
-    shift 
-    ;;
-  -f | --file-manager)
+	case "$1" in
+	-d | --directory)
+		dir="$2"
+		shift 2
+		;;
+	-v | --vim)
+		v=true
+		shift 
+		;;
+	-f | --file-manager)
 	f=true
 	shift
 	;;
-  -h | --help)
-    _usage
-    exit 0
-    ;;
-  --)
-    shift
-    break
-    ;;
-  *)
-    echo "error: $1"
-    exit 1
-    ;;
-  esac
+	-h | --help)
+		_usage
+		exit 0
+		;;
+	--)
+		shift
+		break
+		;;
+	*)
+		echo "error: $1"
+		exit 1
+		;;
+	esac
 done
 
 if [ ! -n "$KITTY_PID" ]; then
-  echo "Error: Must be launched using kitty as your terminal."
-  exit 1
+	echo "Error: Must be launched using kitty as your terminal."
+	exit 1
 fi
 if [ ! -z "$@" ]; then
-  echo "Invalid option(s) \"$@\""
-  _usage
-  exit 1
+	echo "Invalid option(s) \"$@\""
+	_usage
+	exit 1
 fi
 
 if $v; then
